services:
  - type: web
    name: task-manager-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: task-manager-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: LOG_LEVEL
        value: info
      - key: CLIENT_URL
        value: https://3ddxtaskmanager.netlify.app

databases:
  - name: task-manager-db
    databaseName: taskmanager
    user: taskmanager_user